"""Generate bundled tech-logo path data (Simple Icons, CC0) for the phone and the desktop."""
import json, re, sys
SI = '/tmp/si/package'
SLUGS = ["python","typescript","javascript","dart","flutter","kotlin","openjdk","go","rust","c","cplusplus","dotnet",
 "php","ruby","swift","html5","css","sass","gnubash","react","nextdotjs","nodedotjs","vuedotjs","svelte","tailwindcss",
 "docker","electron","vite","markdown","yaml","json","lua","r","scala","elixir","haskell","zig","julia","jupyter",
 "latex","gradle","android","angular","django","fastapi","flask","deno","bun","postgresql","sqlite","toml","nixos","vim"]
ALIASES = {  # GitHub linguist / agent language names (lower-case) -> slug
 "python":"python","jupyter notebook":"jupyter","typescript":"typescript","tsx":"typescript","javascript":"javascript","jsx":"javascript",
 "dart":"dart","flutter":"flutter","kotlin":"kotlin","java":"openjdk","go":"go","golang":"go","rust":"rust","c":"c","c++":"cplusplus",
 "cpp":"cplusplus","objective-c":"c","c#":"dotnet","csharp":"dotnet","f#":"dotnet",".net":"dotnet","php":"php","ruby":"ruby","swift":"swift",
 "html":"html5","css":"css","scss":"sass","sass":"sass","less":"css","shell":"gnubash","bash":"gnubash","zsh":"gnubash","powershell":"gnubash",
 "react":"react","next.js":"nextdotjs","nextjs":"nextdotjs","node.js":"nodedotjs","node":"nodedotjs","nodejs":"nodedotjs","vue":"vuedotjs",
 "vue.js":"vuedotjs","svelte":"svelte","tailwind":"tailwindcss","tailwind css":"tailwindcss","tailwindcss":"tailwindcss","docker":"docker",
 "dockerfile":"docker","electron":"electron","vite":"vite","markdown":"markdown","mdx":"markdown","yaml":"yaml","json":"json","lua":"lua",
 "r":"r","scala":"scala","elixir":"elixir","haskell":"haskell","zig":"zig","julia":"julia","tex":"latex","latex":"latex","gradle":"gradle",
 "android":"android","angular":"angular","django":"django","fastapi":"fastapi","flask":"flask","deno":"deno","bun":"bun","sql":"postgresql",
 "plpgsql":"postgresql","postgresql":"postgresql","sqlite":"sqlite","toml":"toml","nix":"nixos","vim script":"vim","vim":"vim",
}
data = {d["slug"] if "slug" in d else None: d for d in []}
meta = json.load(open(f"{SI}/data/simple-icons.json"))
meta = meta["icons"] if isinstance(meta, dict) else meta
def slugify(t):
    # simple-icons slug rules (approx.) for entries without an explicit slug
    t = t.lower().replace("+", "plus").replace(".", "dot").replace("&", "and").replace("#", "sharp")
    return re.sub(r"[^a-z0-9]", "", t)
by = {(m.get("slug") or slugify(m["title"])): m for m in meta}
out = []
for s in SLUGS:
    svg = open(f"{SI}/icons/{s}.svg").read()
    d = re.search(r' d="([^"]+)"', svg).group(1)
    m = by.get(s)
    if not m:
        sys.exit("no meta " + s)
    out.append({"slug": s, "title": m["title"], "hex": m["hex"], "d": d})
version = json.load(open(f"{SI}/package.json"))["version"]
hdr = f"Generated by /workspace/work/nvsocial-icons/gen.py from Simple Icons {version} (CC0 1.0, https://simpleicons.org). Brand logos remain trademarks of their owners."
# Dart
with open(sys.argv[1], "w") as f:
    f.write(f"// {hdr}\n// ignore_for_file: lines_longer_than_80_chars\n\n")
    f.write("class TechIconData {\n  const TechIconData(this.slug, this.title, this.hex, this.path);\n  final String slug, title, hex, path;\n}\n\n")
    f.write("const Map<String, TechIconData> kTechIcons = {\n")
    for i in out:
        f.write(f"  {json.dumps(i['slug'])}: TechIconData({json.dumps(i['slug'])}, {json.dumps(i['title'])}, {json.dumps(i['hex'])}, {json.dumps(i['d']).replace('$', chr(92)+'$')}),\n")
    f.write("};\n\n/// GitHub linguist / agent language names (lower-case) -> icon slug.\nconst Map<String, String> kTechAliases = {\n")
    for k, v in ALIASES.items():
        f.write(f"  {json.dumps(k)}: {json.dumps(v)},\n")
    f.write("};\n")
# TS
with open(sys.argv[2], "w") as f:
    f.write(f"// {hdr}\n/* eslint-disable */\n\nexport interface TechIconData {{\n  hex: string\n  path: string\n  slug: string\n  title: string\n}}\n\n")
    f.write("export const TECH_ICONS: Record<string, TechIconData> = " + json.dumps({i['slug']: {"hex": i['hex'], "path": i['d'], "slug": i['slug'], "title": i['title']} for i in out}, indent=1) + "\n\n")
    f.write("/** GitHub linguist / agent language names (lower-case) -> icon slug. */\nexport const TECH_ALIASES: Record<string, string> = " + json.dumps(ALIASES, indent=1) + "\n")
print(len(out), "icons")
