import { cn } from '@/lib/utils'
import { useTheme } from '@/themes'

const assetPath = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`

// Brand badge: the Neovarch halo-N mark in the app-icon squircle. Both modes
// use the crimson tile (it reads on bone and on ink surfaces alike); the PNG
// carries the rounded shape and transparent corners, so no tile/rounding
// classes here. Generated by tools/gen_icons.py from the brand app icon; size
// via className (default size-14).
export function BrandMark({ className, ...props }: React.ComponentProps<'span'>) {
  const { renderedMode } = useTheme()
  const dark = renderedMode === 'dark'

  return (
    <span className={cn('inline-flex size-14 shrink-0 items-center justify-center', className)} {...props}>
      <img alt="" className="size-full object-contain" src={assetPath(dark ? 'neovarch-mark-dark.png' : 'neovarch-mark.png')} />
    </span>
  )
}
